USE AutoShow;

DROP TABLE IF EXISTS TestDrive;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Specifications;
DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Label;
DROP TABLE IF EXISTS Manufacturer;
DROP TABLE IF EXISTS Material;
DROP TABLE IF EXISTS `Status`;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Colour;
DROP TABLE IF EXISTS Country;
